
##############################
###### Pour la HomePage#######
##############################

tea_homepage:
    path:     /
    defaults: { _controller: TeaCampusCommonBundle:Default:index }

##############################
###### Pour A Propos   #######
##############################

tea_about:
    path:     /about
    defaults: { _controller: TeaCampusCommonBundle:Default:about }
    
tea_faq:
    path:     /faq
    defaults: { _controller: TeaCampusCommonBundle:Default:faq }
    
############################################
###### Pour les videos de formations #######
############################################

tea_formations:
    path:     /formations
    defaults: { _controller: TeaCampusCommonBundle:Formation:index }
    
tea_formations_subject:
    path:     /formations/{subject}
    defaults: { _controller: TeaCampusCommonBundle:Formation:subject }
    
tea_formations_chapter:
    path:     /formations/{subject}/{chapter}
    defaults: { _controller: TeaCampusCommonBundle:Formation:chapter }
    
tea_formations_show:
    path:     /formations/{subject}/{chapter}/videos/{id}
    defaults: { _controller: TeaCampusCommonBundle:Formation:video }
    
tea_formations_search:
    path:     /formations/search
    defaults: { _controller: TeaCampusCommonBundle:Formation:search }
    
tea_formations_tag:
    path:     /formations/tag/{tag}
    defaults: { _controller: TeaCampusCommonBundle:Formation:tag }
    
tea_videos_delete:
    path:     /formations/videos/delete/
    defaults: { _controller: TeaCampusCommonBundle:Formation:delete }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
 

##############################
###### Pour les projets ######
##############################

tea_projects:
    path:     /projects
    defaults: { _controller: TeaCampusCommonBundle:Projet:index }
    
tea_projects_list:
    path:     /projects/all
    defaults: { _controller: TeaCampusCommonBundle:Projet:list }
    
tea_projects_show:
    path:     /projects/{id}
    defaults: { _controller: TeaCampusCommonBundle:Projet:show }
    requirements:
        id:  \d+
    
tea_projects_add:
    path:     /projects/add
    defaults: { _controller: TeaCampusCommonBundle:Projet:add }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
    
tea_projects_edit:
    path:     /projects/edit/{id}
    defaults: { _controller: TeaCampusCommonBundle:Projet:edit }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
    
tea_projects_delete:
    path:     /projects/delete/
    defaults: { _controller: TeaCampusCommonBundle:Projet:delete }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
    
tea_projects_tag:
    path:     /projects/tag/{tag}
    defaults: { _controller: TeaCampusCommonBundle:Projet:tag }
    
tea_projects_search:
    path: /projects/search/
    defaults: { _controller: TeaCampusCommonBundle:Projet:search }
    
##############################
######      Autres     #######
##############################

tea_forum:
    path:     /forum
    defaults: { _controller: TeaCampusCommonBundle:Default:forum }
    
tea_contacts:
    path:     /contacts
    defaults: { _controller: TeaCampusCommonBundle:Contact:index }
    
tea_contacts_send:
    path:     /contacts/send
    defaults: { _controller: TeaCampusCommonBundle:Contact:send }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
    
tea_mentions:
    path:     /mentions-legales
    defaults: { _controller: TeaCampusCommonBundle:Default:mentions }
