
sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      TeaCampus
    title_logo: bundles/teacampuscommon/images/logos/logo.png
    options:
        html5_validate: false # does not use html5 validation
        pager_links: 5 # pager max links to display

    templates:
        # default global templates
        # the layout template include javascript/stylesheet to the formatter bundle,
        # if you don't need it use the default one: SonataAdminBundle::standard_layout.html.twig
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
#            - { position: left, type: sonata.admin.block.admin_list }
#            - { position: right, type: sonata.admin_doctrine_orm.block.audit}
            #- { position: left, type: sonata.block.service.text, settings: { content: "<div class='panel panel-default'><div class='panel-heading'><h3 class='panel-title'>Welcome!</h3></div><div class='panel-body'>You can customize this dashboard by editing the <code>sonata_admin.yml</code> file. The current dashboard presents the recent items from the NewsBundle and a non-statistical e-commerce information.</div></div>"} }
            # This block is disabled for now as the bundle generates an exception with composite key
#            - { position: left, type: sonata.timeline.block.timeline, settings: { context: SONATA_ADMIN, max_per_page: 25 }}
            #- { position: left, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 7, mode: admin }}
            #- { position: left, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 7, mode: admin }}
            #- { position: right, type: sonata.customer.block.recent_customers, settings: { title: Recent Customers, number: 5, mode: admin }}
            #- { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss, template: SonataAdminBundle:Block:block_rss_dashboard.html.twig }}

        groups:
            sonata.admin.group.content:
                label:           Général
                label_catalogue: TeaCampusCommonBundle
                icon:            '<i class="fa fa-keyboard-o"></i>'
                items:
                    - tea.admin.concours
                    - tea.admin.advert
                    - tea.admin.event
                    - tea.admin.tea_and_me
            
            sonata.admin.group.tea:
                label:           T.E.A
                label_catalogue: TeaCampusCommonBundle
                icon:            '<i class="fa fa-coffee"></i>'
                items:
                    - tea.admin.testimony
                    - tea.admin.faq
                    - tea.admin.history
                    - tea.admin.service
                    - tea.admin.partner
            
            sonata.admin.group.projects:
                label:           Projets
                label_catalogue: TeaCampusCommonBundle
                icon:            '<i class="fa fa-book"></i>'
                items:
                    - tea.admin.projet
                    
            sonata.admin.group.formation:
                label:           Formation
                label_catalogue: TeaCampusCommonBundle
                icon:            '<i class="fa fa-graduation-cap"></i>'
                items:
                    - tea.admin.video
                    - tea.admin.tutoring_request
                    
            sonata.admin.group.news:
                label:           Actualité
                label_catalogue: SonataNewsBundle
                icon:            '<i class="fa fa-newspaper-o"></i>'
                items:
                    - sonata.news.admin.post
                    
            sonata.admin.group.media:
                label:           Mediatheque
                label_catalogue: SonataMediaBundle
                icon:            '<i class="fa fa-film"></i>'
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery


            sonata.admin.group.classification:
                label:           sonata_classification
                label_catalogue: SonataClassificationBundle
                icon:            '<i class="fa fa-sitemap"></i>'
                items:
                    - sonata.classification.admin.category
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.collection
                    - sonata.classification.admin.context


            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.badge
                    - sonata.user.admin.group
                    - tea.admin.cv
                    #- sonata.page.admin.site
                    #- sonata.notification.admin.message


    assets:
        stylesheets:
            # The sandbox includes default pre-optimized version of some css and js
            # So you can either use them, and add your custom assets here
            #   ~ or ~
            # tweak the assetic.yml and the following lines

            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css

            - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css

            - bundles/bmatznerfontawesome/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css

            - bundles/sonataadmin/vendor/jqueryui/themes/flick/jquery-ui.min.css

            - bundles/sonataadmin/vendor/select2/select2.css
            - bundles/sonataadmin/vendor/select2/select2-bootstrap.css

            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

            - bundles/sonataformatter/markitup/skins/sonata/style.css
            - bundles/sonataformatter/markitup/sets/markdown/style.css
            - bundles/sonataformatter/markitup/sets/html/style.css
            - bundles/sonataformatter/markitup/sets/textile/style.css

            
            

        javascripts:
            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.core.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.widget.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.mouse.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.draggable.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.droppable.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.resizable.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.selectable.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.sortable.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.accordion.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.autocomplete.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.button.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.datepicker.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.dialog.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-blind.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-bounce.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-clip.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-drop.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-explode.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-fade.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-fold.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-highlight.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-pulsate.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-scale.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-shake.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-slide.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-transfer.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.menu.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.position.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.progressbar.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.slider.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.spinner.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.tabs.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.tooltip.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js

            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js

            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.js
            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonataadmin/vendor/select2/select2.min.js

            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js

            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js
            - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
            - bundles/sonataformatter/markitup/sets/markdown/set.js
            - bundles/sonataformatter/markitup/sets/html/set.js
            - bundles/sonataformatter/markitup/sets/textile/set.js
            