<?php

namespace AndreMarvell\NotificationBundle\Entity\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUnread($receiver)
    {
        $qb =  $this->createQueryBuilder('n');
        $qb ->innerJoin('n.receiver', 'u')
            ->where('u.id = :receiver')
            ->setParameter('receiver', $receiver)
            ->orderBy('n.date', 'DESC')
            ->setMaxResults(30);
        
        try {
            return $qb->getQuery()
                  ->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
