<?php

namespace TeaCampus\CommonBundle\Entity\Repository;

/**
 * IngredientRepository
 * By : SAMIE MEHEZA
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getSelectedProjet() {
        $query = $this->createQueryBuilder('a');
        $query->where('a.selectionOfTea =  true ');
        $query->andWhere('a.private = false');
        return $query->getQuery()->getResult();
    }
    
    public function getProjectOfTheMonth() {
        $query = $this->createQueryBuilder('a');
        $query->where('a.projectOfTheMonth =  true ');
        $query->andWhere('a.private = false');
        return $query->getQuery()->getResult();
    }
    
    public function getProjectOfTheWeek() {
        $query = $this->createQueryBuilder('a');
        $query->where('a.projectOfTheWeek =  true ');
        $query->andWhere('a.private = false');
        return $query->getQuery()->getResult();
    }
    
    public function findMostRead() {
 
        $query = $this->createQueryBuilder('p');
        $query->where('p.private = false ');
        $query->orderBy('p.date','DESC');
        $query->setMaxResults(5);
        
        return $query->getQuery()->getResult();
    }
}
