<?php

namespace TeaCampus\CommonBundle\Entity\Repository;

/**
 * TeaAndMeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeaAndMeRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($search, $limit = null)
    {
        $query = $this->createQueryBuilder('t');
        $query->where($query->expr()->like('t.title', ':search'))
              ->setParameter('search', '%'.$search.'%');
        if(!is_null($limit)){
            $query->setMaxResults($limit);
        }
 
        return $query->getQuery()->getResult();
    }
}
