<?php

namespace Application\Sonata\ClassificationBundle\Entity;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategories($locale='fr') {
 
        $query = $this->createQueryBuilder('c');
        $query->leftJoin('c.context', 'context');
        $query->leftJoin('c.parent', 'parent');
        $query->innerJoin('c.children', 'children');
        $query->where('c.enabled = true ');
        //$query->having($query->expr()->gte($query->expr()->count('children'), 0));
        $query->andWhere($query->expr()->like('c.locale',':locale'))->setParameter('locale',$locale);
        $query->andWhere($query->expr()->like('context.name',':cntxt'))->setParameter('cntxt','video');
        $query->orderBy('c.position','ASC');
        
//        echo '<pre>';
//        \Doctrine\Common\Util\Debug::dump($query->getQuery()->getResult());
//        echo '</pre>';
//        exit;
        return $query->getQuery()->getResult();
    }
}
